class States:
    SUGGEST_TASK = "SUGGEST_TASK"
    SUGGEST_ONE_MORE_TASK = "SUGGEST_ONE_MORE_TASK"
    ASK_COHERENCE = "ASK_COHERENCE"
    ASK_XSTS = "ASK_XSTS"
    ASK_TRANSLATION = "ASK_TRANSLATION"
